import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { load, nameArgument, root, save, wrangler } from "./config";
const state = await load(nameArgument(), true);
if (state.account && process.env.CLOUDFLARE_ACCOUNT_ID !== state.account) throw new Error("Use the same CLOUDFLARE_ACCOUNT_ID as the saved deployment");
const cargo = await readFile(resolve(root, "../Cargo.toml"), "utf8");
const version = /^version = "([^"]+)"/m.exec(cargo)?.[1];
if (!version) throw new Error("Missing xrun release version");
const config = JSON.parse(await readFile(resolve(root, "wrangler.jsonc"), "utf8"));
config.name = state.name;
config.main = "../src/index.ts";
config.vars = { XRUN_VERSION: version };
const configPath = resolve(root, ".deploy", `${state.name}.wrangler.json`);
await writeFile(configPath, JSON.stringify(config, null, 2), { mode: 0o600 });
console.log(`Deploying ${state.name} (${version})…`);
const output = await wrangler(["deploy", "--config", configPath]);
const url = /https:\/\/[a-z0-9-]+\.[a-z0-9-]+\.workers\.dev/.exec(output)?.[0];
if (!url) throw new Error("Wrangler did not return a workers.dev address");
await wrangler(["secret", "put", "RELAY_ROUTE", "--config", configPath], state.route + "\n");
state.url = url;
await save(state);
console.log(`\nRelay address: ${url}/${state.route}\n`);
console.log("Use this full address in the App or xrun up --relay. Keep the address private.");
