//! User operations on network identity and membership.
use crate::{
    config::{self, Identity},
    error::ErrorCode,
    net,
    protocol::*,
};
use anyhow::{Result, bail};
use serde::{Deserialize, Serialize};
#[derive(Debug, Serialize)]
/// Saved single-device access policy after any running daemon acknowledged a reload.
pub struct Permission {
    /// Immutable source ID whose local access rule was changed.
    pub source_device_id: String,
    /// Whether this individual grant allows access; global pause and denials still apply.
    pub allowed: bool,
}
#[derive(Debug, Serialize)]
/// Saved registration, without daemon initialization or service startup.
pub struct JoinInfo {
    /// Immutable device ID of the saved registration.
    pub device_id: String,
    /// Device name recorded in the verified roster.
    pub name: String,
    /// Signed inviter policy recorded when the identity joined.
    pub registration: Registration,
    /// Network identifier derived from its root public key.
    pub network_id: String,
    /// Signed relay endpoints used by the saved identity.
    pub relay_addresses: Vec<String>,
}
/// Register with a one-use invitation and save identity and any signed mutual grant.
/// Success does not start or initialize the daemon; failures retain a pending key for
/// safe retry. An already joined identity must remain in the same network.
pub async fn join(link: &str, name: Option<String>) -> Result<JoinInfo> {
    let id = super::join_identity(link, name).await?;
    joined(id)
}
fn joined(id: Identity) -> Result<JoinInfo> {
    let network_id = crate::network::authority(&id)?.network_id.clone();
    Ok(JoinInfo {
        device_id: id.device_id,
        name: id.name,
        registration: id.registration,
        network_id,
        relay_addresses: id.addresses,
    })
}

/// Create and publish a manager identity. Success means registration is saved,
/// not that the daemon is initialized or running. Retryable publication failures
/// retain pending authority, and never create a second root on retry.
pub async fn create_network(link: &str, name: Option<String>) -> Result<JoinInfo> {
    joined(crate::network::create(link, name).await?)
}

/// A single-use, ten-minute invitation generated by the network manager.
#[derive(Debug, Serialize, Deserialize)]
pub struct Invitation {
    /// Secret bearer link; show or copy only after a successful request.
    pub link: String,
    /// Whether accepting the link grants mutual access with the inviter.
    pub allow: bool,
    /// Remaining validity in seconds at creation.
    pub expires_in: u64,
}

/// Generate an invitation after publishing the manager's current signed roster.
/// Requires the manager identity. `allow` grants mutual execution, file and screenshot
/// access only to the device that consumes this invitation; defaults belong to the UI.
pub async fn invite(allow: bool) -> Result<Invitation> {
    let mut id = Identity::load()?;
    net::renew_identity(&mut id).await?;
    Ok(serde_json::from_value(
        crate::network::invite(&id, allow).await?,
    )?)
}

/// Local revocation result, with independent remote delivery information.
#[derive(Debug, Serialize, Deserialize)]
pub struct Revocation {
    /// Immutable ID of the revoked member.
    pub device_id: String,
    /// The manager's signed roster has committed the revocation locally.
    pub revoked: bool,
    /// Version of the locally committed roster.
    pub roster_version: u64,
    /// Active remote members that did not confirm this version.
    pub undelivered: Vec<String>,
    /// Device discovery or synchronization failure after local commit, if any.
    pub sync_error: Option<String>,
}

/// Commit a member revocation and attempt delivery. Requires the manager identity;
/// its own identity cannot be revoked. A successful result remains locally effective
/// even when `sync_error` or `undelivered` is nonempty. Retry is idempotent and tries
/// delivery again; offline endpoints enforce revocation after receiving the roster.
pub async fn revoke(device: &str) -> Result<Revocation> {
    let mut id = Identity::load()?;
    net::renew_identity(&mut id).await?;
    Ok(serde_json::from_value(
        crate::network::revoke(&id, device).await?,
    )?)
}

/// Persist access for all current and future members, retaining individual grants
/// and denials, then wait for a running daemon to reload it. Denials take priority.
/// Reload errors do not roll back the already saved configuration.
pub async fn set_all_permissions(allow: bool) -> Result<()> {
    config::update_all_permissions(allow)?;
    crate::control::refresh_access().await
}

/// Persist the remote-access pause and wait for a running daemon to reload it.
/// Permissions remain saved; pausing closes authorized peer sessions without
/// canceling accepted background jobs. Reload failure does not undo the saved pause.
pub async fn pause_access(paused: bool) -> Result<()> {
    config::pause_remote_access(paused)?;
    crate::control::refresh_access().await
}
/// Persist an allow or deny rule for an immutable ID or resolved member name, then
/// wait for a running daemon to reload it. IDs work while offline; names require a
/// verified roster. Reload errors leave the configuration saved. No job is canceled.
pub async fn set_permission(value: &str, allow: bool) -> Result<Permission> {
    let id = Identity::load()?;
    let device_id = if let Some(key) = value.strip_prefix("dev_") {
        if key.len() != 32 || !key.bytes().all(|b| b.is_ascii_hexdigit()) {
            bail!(
                ErrorCode::InvalidDeviceId.error("expected dev_ followed by 32 hexadecimal digits")
            );
        }
        value.to_string()
    } else {
        let device: Device = net::http(
            &id,
            reqwest::Method::GET,
            &format!("/devices/{value}"),
            None,
        )
        .await?;
        device.device_id
    };
    config::update_permission(&device_id, allow)?;
    crate::control::refresh_access().await?;
    Ok(Permission {
        source_device_id: device_id,
        allowed: allow,
    })
}
