name: Test Windows
on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  test:
    runs-on: windows-2022
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756
        with:
          arch: x64
      - name: Rust toolchain
        shell: bash
        run: |
          rustup update stable
          rustup default stable
          rustup component add rustfmt clippy
      - name: Format, lint and test
        shell: bash
        run: |
          cargo fmt --all -- --check
          cargo clippy --locked --all-targets -- -D warnings
          cargo test --locked
